### ISSUE TITLE
这个可以和awtk designer联动吗

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk-jerryscript#11]
目前想法是用awtk designer设计xml ui, 后台逻辑用javascript设计，看了下1.2.2的版本可以打开这个项目，可以显示部分Ui, 就是非常老（0.1.5版本），发现能识别jerryscript插件，但是awtkStudio自带的sdk无法编译，只能用github上下的awtk，问下这个后面考虑更新支持吗

![image](https://github.com/zlgopen/awtk-jerryscript/assets/54085641/3fb4d7c3-071d-4ad0-b535-79b144ded523)

**Comment by Tracker647** [comment]
自己摸索出了一个方法做参考：
https://blog.csdn.net/Tracker647/article/details/139306235

两个问题：
1.不知团队后期有无让designer支持js编程的设想呢，比如图形界面设置事件自动填充代码。
2.项目部署到web后可不可以自己整合web的3d库进去，比如wed3d，方便浏览器上的开发

**Comment by Tracker647** [comment]
新问题，自己尝试用designer弄了个页面，然后用js写逻辑，发现用TWindow.open()打开正常，但是后面写事件注册直接就闪退了，麻烦跟踪一下看看为什么。
awtk版本：1.1.0（在designer里面改了sdk路径）
designer版本：1.2.2

![GIF 2024-5-30 12-04-40](https://github.com/zlgopen/awtk-jerryscript/assets/54085641/75516936-a3bb-40c0-92d0-13f0d7c65b3e)
窗口打印如下：
![image](https://github.com/zlgopen/awtk-jerryscript/assets/54085641/e44519cc-d694-4b69-8763-55a85a1d26a0)

**Comment by xianjimli** [comment]
1.不知团队后期有无让designer支持js编程的设想呢，比如图形界面设置事件自动填充代码。
> 用vscode + designer配合开发。vscode 安装copilot之后非常好用。

2.项目部署到web后可不可以自己整合web的3d库进去，比如wed3d，方便浏览器上的开发
> 这个可能不行，awtk用的2d canvas

**Comment by xianjimli** [comment]
新问题，自己尝试用designer弄了个页面，然后用js写逻辑，发现用TWindow.open()打开正常，但是后面写事件注册直接就闪退了，麻烦跟踪一下看看为什么。
> 把home_page.xml贴上来看看

**Comment by Tracker647** [comment]
home_page.xml
```
<window name="home_page">
  <button name="button" x="200" y="330" w="100" h="36" text="Button"/>
  <button name="button1" x="363" y="330" w="100" h="36" text="Button"/>
  <button name="button2" x="521" y="330" w="100" h="36" text="Button"/>
  <label name="label" x="327" y="264" w="160" h="28" text="Label"/>
</window>
```

**Comment by xianjimli** [comment]
重新生成资源了吗，我这里没问题。你试试这段代码：
```js
function applicationInit() {
  var win = TWindow.open('home_page');
  var ok = win.lookup('button', true).on(TEventType.CLICK, function(evt) {
    var e = TPointerEvent.cast(evt);
    var target = TButton.cast(e.target);

    console.log("click at " + e.x + " " + e.y + " on " + target.name);
    console.log("global: " + TGlobal.getPointerX() + " " + TGlobal.getPointerY() + " " + TGlobal.isPointerPressed());

    return TRet.OK;
  }); 
  
  console.log("global: " + TGlobal.getPointerX() + " " + TGlobal.getPointerY() + " " + TGlobal.isPointerPressed());

  win.layout();
}

applicationInit()
```

**Comment by xianjimli** [comment]
js文件放到design/default/scripts/目录下，修改后要重新生成资源。
比如文件名为design/default/scripts/button.js，要这样运行：

```
./bin/awtkRun button
```

**Comment by Tracker647** [comment]
运行正常，那可能是我之前弄错脚本路径和忘记重新资源了
