### ISSUE TITLE
编译时报错  error: use of undeclared identifier 'EVT_DONE' 环境macos

### ISSUE THREAD

**Issue by ElliottSeer** [zlgopen/awtk-jerryscript#3]
报错信息如下
src/c/tk_jerryscript.c:2307:34: error: use of undeclared identifier 'EVT_DONE';
      did you mean 'EVT_NONE'?
  return jsvalue_create_int(ctx, EVT_DONE);
                                 ^~~~~~~~
                                 EVT_NONE
/Users/zhangyuchen/Work/code/awtk/src/tkc/event.h:40:3: note: 'EVT_NONE'
      declared here
  EVT_NONE = 0,
  ^
src/c/tk_jerryscript.c:16854:28: warning: implicit declaration of function
      'file_chooser_cast' is invalid in C99 [-Wimplicit-function-declaration]
    ret = (file_chooser_t*)file_chooser_cast(data);
                           ^
src/c/tk_jerryscript.c:16854:11: warning: cast to 'file_chooser_t *' (aka
      'struct _file_chooser_t *') from smaller integer type 'int'
      [-Wint-to-pointer-cast]
    ret = (file_chooser_t*)file_chooser_cast(data);
          ^
src/c/tk_jerryscript.c:16915:24: warning: implicit declaration of function
      'file_chooser_get_dir' is invalid in C99 [-Wimplicit-function-declaration]
    ret = (const char*)file_chooser_get_dir(chooser);
                       ^
src/c/tk_jerryscript.c:16915:11: warning: cast to 'const char *' from smaller
      integer type 'int' [-Wint-to-pointer-cast]
    ret = (const char*)file_chooser_get_dir(chooser);
          ^
src/c/tk_jerryscript.c:16930:24: warning: implicit declaration of function
      'file_chooser_get_filename' is invalid in C99
      [-Wimplicit-function-declaration]
    ret = (const char*)file_chooser_get_filename(chooser);
                       ^
src/c/tk_jerryscript.c:16930:11: warning: cast to 'const char *' from smaller
      integer type 'int' [-Wint-to-pointer-cast]
    ret = (const char*)file_chooser_get_filename(chooser);
          ^
src/c/tk_jerryscript.c:16944:19: warning: implicit declaration of function
      'file_chooser_is_aborted' is invalid in C99
      [-Wimplicit-function-declaration]
    ret = (bool_t)file_chooser_is_aborted(chooser);
                  ^
7 warnings and 1 error generated.
scons: *** [src/c/tk_jerryscript.o] Error 1
scons: building terminated because of errors.

**Comment by xianjimli** [comment]
好的，谢谢。麻烦更新一下AWTK和AWTK-jerryscript。
