### ISSUE TITLE
win10下编译报错 无法解析的外部符号 scanner_scan_bracket scanner_check_directives

### ISSUE THREAD

**Issue by ElliottSeer** [zlgopen/awtk-jerryscript#4]
成功编译awtk， 但在尝试编译awtk-jerryscript遇到：
  正在创建库 bin\awtkRun.lib 和对象 bin\awtkRun.exp
jerryscript.lib(jerry-all-in.obj) : error LNK2019: 无法解析的外部符号 scanner_scan_bracket，该符号在函数 scanner_scan_primary_expression 中被引用
jerryscript.lib(jerry-all-in.obj) : error LNK2019: 无法解析的外部符号 scanner_check_directives，该符号在函数 scanner_scan_all 中被引用
bin\awtkRun.exe : fatal error LNK1120: 2 个无法解析的外部命令
scons: *** [bin\awtkRun.exe] Error 1120
scons: building terminated because of errors.

编译环境 visual studio 2019 / Windows 10 SDK (10.0.17763.0)
python 3.7.6

**Comment by xianjimli** [comment]
记得这个问题前几天已经改了，awtk-jerryscript 是最新的吗？

**Comment by ElliottSeer** [comment]
> 记得这个问题前几天已经改了，awtk-jerryscript 是最新的吗？

是直接clone的master分支

**Comment by xianjimli** [comment]
我改了，你再更新一下。

**Comment by ElliottSeer** [comment]
成功运行！！感谢！！
